#!/bin/bash

readonly command="$1"
readonly args="$(echo -n ${@:2} | $(dirname $0)/json_escape)"


if [[ -n $EDI_METADATA ]]; then
    EDI_METADATA=",\"meta\":${EDI_METADATA}"
fi

json="{\"cmd\":\"${command}\",\"args\":${args},\"user\":\"${USERNAME:-emit-cmd}\",\"src\":\"na\"${EDI_METADATA}}"

if [[ -z $command ]]; then
    echo "USAGE: $0 <command> [args]"
    exit 1
fi

amqp-publish -u "amqp://${AMQP_SERVER:-localhost}" -e cmd -r "$command" \
	     --content-type="application/json" \
	     -b "${json}"
