#!/bin/bash -x

command="$1"
args="${@:2}"
json="{\"cmd\":\"${command}\",\"args\":\"${args}\",\"user\":\"emit-cmd\",\"src\":\"na\"}"


if [[ -z $command ]]; then
    echo "USAGE: $0 <command> [args]"
    exit 1
fi

amqp-publish -u "amqp://${AMQP_SERVER:-localhost}" -e cmd -r "$command" \
	     --content-type="application/json" \
	     -b "${json}"
