#!/bin/bash

case "$1" in
    start)
	emit_cmd tts --voice lea --text Subraum startet
	emit_cmd sob subraum_startup
	;;
    stop)
	emit_cmd tts --voice lea --text Subraum faehrt runter
	emit_cmd sob subraum_shutdown
        ;;
esac
