#!/bin/bash

case "$1" in

    start)
	emit-cmd act bulb on
	emit-cmd act sofaleds on
	emit-cmd act dmx all green
	;;

    stop)
	emit-cmd act bulb off
	emit-cmd act sofaleds off
	emit-cmd act dmx all black
	;;

esac
