#!/bin/bash

SCRIPTPATH=$(dirname $0)

filename_tags () {
    gawk '
BEGIN {
   RS="\x00";
}
{
   t = $0;
   gsub(/.+\//,"", t);
   gsub(/\.\w+$/,"",t);
   gsub(/[\W_\.]/," ",t);
   print t
}' -
}

find "${SCRIPTPATH}/files" -mindepth 1 |
    while read filename; do
	echo "$filename"
	index_file="index/$(basename $filename)"
	echo $filename | filename_tags | tee $index_file
	"${SCRIPTPATH}/metadata_tags" 2>/dev/null $filename | tee -a $index_file
    done
