#!/bin/sh

exec 2>&1

cd ${APPDIR}/soundboard

echo "Generating index"
./make_index

exec chpst -e "$ENVDIR" \
     listen_command \
     --cmd sob \
     --data onlyargs \
     --name "soundboard" \
     --description "SOundBoard" \
     --exe "${APPDIR}/soundboard/edimq-handler"
