#!/bin/sh

exec 2>&1

cd ${APPDIR}/proc/soundboard

echo "Generating index"
./make_index

exec chpst -e "$ENVDIR" \
     ${APPDIR}/misc/listen_command \
     --cmd sob \
     --data onlyargs \
     --name "soundboard" \
     --description "SOundBoard - Feed me: git.c3pb.de:irq0/edi.git proc/soundboard/files" \
     --exe "${APPDIR}/proc/soundboard/edimq-handler"
