#!/bin/bash -x

set -o errexit
set -o nounset

readonly SCRIPTPATH="$(dirname "$0")"

readonly SCRIPTS_DEFAULT="$SCRIPTPATH/DEFAULT"
readonly SCRIPTS_ALWAYS="$SCRIPTPATH/ALWAYS"
readonly SCRIPTS_USER="$SCRIPTPATH/users"

find_script () {
    local user="$1"
    local event="$2"
    local user_script="${SCRIPTS_USER}/${user}/${event}"
    local default_script="${SCRIPTS_DEFAULT}/${event}"
    local always_script="${SCRIPTS_ALWAYS}/${event}"

    if [[ -x $always_script ]];then
	echo "$always_script"
    fi

    if [[ -x $user_script ]]; then
	echo "$user_script"
	return 0
    elif [[ -x $default_script ]]; then
	echo "$default_script"
	return 0
    else
	return 1
    fi
}

main () {
    if [[ $EDI_CMD =~ ^[a-z\.-]+$ && $EDI_USER =~ ^[a-zA-Z0-9]+$ ]]; then
	local event="${EDI_CMD#*.}"
	echo "SUP: for_user=$EDI_USER event=$event" >&2
	local scripts="$(find_script "$EDI_USER" "$event")"

	for script in $scripts; do
	    echo "SUP: exec $script" >&2
	    exec "$script"
	done
    fi
}

main
