#!/bin/bash

INDEXPATH="$(dirname "$0")/index"
FILEPATH="$(dirname "$0")/files"
key="$(printf "%s " "${@}")"

file="$(tre-agrep \
    --best-match \
    --ignore-case \
    --files-with-matches \
    "$key" \
    ${INDEXPATH}/* \
| sort -R \
| head -1)"

echo "${FILEPATH}/$(basename "$file")"
