#!/bin/bash

INDEXPATH="$(dirname $0)/index"
FILEPATH="$(dirname $0)/files"
files="$(find ${INDEXPATH} -mindepth 1)"

key=$@

file="$(tre-agrep \
    --best-match \
    --ignore-case \
    --files-with-matches \
    "$key" \
    $files \
| sort -R \
| head -1)"

echo "${FILEPATH}/$(basename $file)"
