#!/bin/bash -x

SCRIPTPATH=$(dirname $0)

file_info () {
    tn=$(mediainfo --Inform="General;%Track%" "$file")

    if [[ -z $tn ]]; then
	echo "$(basename "$file")"
    else
	echo "$tn"
    fi
}

read search
echo "Search keyword: $search"
file="$(${SCRIPTPATH}/approx_find_file ${search})"

emit_msg "SOB: $(file_info "$file")"
emit_notification "$file"
