#!/bin/bash

mediainfo "$1" |
    gawk '
BEGIN {
   FS="[[:space:]]+:[[:space:]]+";
   OFS="\x1E";
   delete tags[0];
}
function add(X) {
   tags[length(tags)+1] = X
}
/Complete name/ {
   filename = $2
}
/(Track name|Performer|Description)/ {
   add($2);
}
END {
   if (filename) {
      for (i=1; i<=length(tags);i++) {
#         print filename, tags[i]
         print tags[i]
      }
   }
}'
