#!/bin/sh

exec 2>&1

export PATH="${PATH}:/usr/games"

exec chpst -e "$ENVDIR" \
     listen_command \
     --cmd fortune \
     --data onlyargs \
     --name "fortune" \
     --description "Please everyone in the room with a fortune cookie" \
     --exe "${APPDIR}/fortune/edimq-handler"
