#!/bin/sh

exec 2>&1

cd ${APPDIR}/proc/weather

exec chpst -e "$ENVDIR" \
     ${APPDIR}/misc/listen_command \
     --cmd weather \
     --cmd wetter \
     --name "weather" \
     --description "Wetterbericht - Subraum und das da draussen" \
     --exe "${APPDIR}/proc/weather/weather-to-msg.sh"
