#!/bin/bash

# EDI Soundboard
#
# Find file from index based on keywords. Use approx matching to
# always return something
#
# Author: Marcel Lauhoff <ml@irq0.org>

INDEXPATH="$(dirname "$0")/index"
FILEPATH="$(dirname "$0")/files"
key="${@}"

candidates="$(tre-agrep \
    --best-match \
    --ignore-case \
    --files-with-matches \
    "$key" \
    ${INDEXPATH}/* \
  | sort -R)"

file="$(echo "$candidates" | head -1)"
ncandidates="$(echo "$candidates" | wc -l)"

echo "$ncandidates:${FILEPATH}/$(basename "$file")" 
