#!/bin/bash

SCRIPTPATH=$(dirname $0)

file_info () {
    tn=$(mediainfo --Inform="General;%Track%" "$file")

    if [[ -z $tn ]]; then
	echo "$(basename "$file")"
    else
	echo "$tn"
    fi
}

read search
echo "Search keyword: $search" >&2

file="$(${SCRIPTPATH}/approx_find_file ${search})"
info="$(file_info "$file")"

echo "Search keyword: $search" >&2
echo "File: $file" >&2
echo "File info: $info" >&2

echo "Soundboard: $info"
emit_notification "$file"
